[project]
name = "StackSwap"
authors = []
description = ""
telemetry = true
requirements = []
[contracts.sip-010-trait]
path = "contracts/sip-010-trait.clar"
depends_on = []

[contracts.stackswap]
path = "contracts/stackswap.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
